const szavak = [
    "alma", "körte", "barack", "szilva", "dió", "mogyoró", "mandula", "eper", "málna", "szeder",
    "ribizli", "áfonya", "citrom", "narancs", "banán", "kiwi", "gránát", "datolya", "füge", "kivi",
    "papaya", "mangó", "ananász", "kókusz", "lime", "avokádó", "cseresznye", "meggy", "szőlő", "dinnye",
    "görög", "sárga", "paradicsom", "uborka", "répa", "zeller", "karalábé", "káposzta", "kelkáposzta", "spenót",
    "sóska", "saláta", "brokkoli", "karfiol", "padlizsán", "cukkini", "tök", "krumpli", "burgonya", "hagyma",
    "fokhagyma", "póréhagyma", "vöröshagyma", "zöldhagyma", "paprika", "csili", "bors", "bab", "borsó", "lencse",
    "csicseriborsó", "szójabab", "kukorica", "rizs", "búza", "árpa", "rozs", "zab", "köles", "hajdina",
    "quinoa", "tönköly", "kamut", "amaránt", "chia", "lenmag", "szezámmag", "napraforgómag", "tökmag", "dió",
    "mogyoró", "mandula", "kesudió", "pisztácia", "mák", "kakaó", "csokoládé", "vanília", "fahéj", "szegfűszeg",
    "szerecsendió", "gyömbér", "kurkuma", "kardamom", "ánizs", "édeskömény", "bazsalikom", "oregánó", "majoránna", "kakukkfű",
    "rozmaring", "zsálya", "menta", "citromfű", "levendula", "petrezselyem", "kapor", "tárkony", "lestyán", "babérlevél",
    "borsikafű", "csombor", "turbolya", "metélőhagyma", "snidling", "torma", "mustár", "ecet", "olaj", "vaj",
    "margarin", "zsír", "szalonna", "kolbász", "sonka", "szalámi", "virsli", "párizsi", "szalonna", "tepertő",
    "hurka", "disznósajt", "csirke", "pulyka", "kacsa", "liba", "marha", "sertés", "bárány", "nyúl",
    "vadhús", "hal", "ponty", "harcsa", "keszeg", "süllő", "pisztráng", "lazac", "tonhal", "szardínia",
    "makréla", "hering", "kagyló", "rák", "homár", "kaviár", "tojás", "tej", "joghurt", "túró",
    "sajt", "vaj", "tejszín", "tejföl", "kefir", "krémsajt", "ricotta", "mascarpone", "parmezán", "mozzarella",
 // igék
        "fut", "ugrik", "úszik", "repül", "olvas", "ír", "beszél", "hallgat", "néz", "lát",
        "eszik", "iszik", "alszik", "ébred", "tanul", "tanít", "dolgozik", "játszik", "sétál", "fekszik",
        "ül", "áll", "megy", "jön", "érkezik", "indul", "vezet", "biciklizik", "főz", "süt",
        "mos", "takarít", "vásárol", "elad", "kér", "ad", "kap", "hoz", "visz", "dob",
        "fog", "enged", "tart", "húz", "tol", "nyit", "zár", "épít", "rombol", "javít",
        "vág", "ragaszt", "fest", "rajzol", "számol", "számít", "programoz", "tervez", "szerkeszt", "fordít",
        "énekel", "táncol", "zenél", "fotóz", "filmez", "játszik", "versenyez", "nyer", "veszít", "küzd",
        "harcol", "véd", "támad", "békül", "barátkozik", "szeret", "gyűlöl", "fél", "remél", "hisz",
        "gondol", "emlékezik", "felejt", "képzel", "álmodik", "tervez", "szervez", "rendez", "vezet", "irányít",
        "ellenőriz", "vizsgál", "kutat", "fedez", "tanulmányoz", "tanít", "tanul", "gyakorol", "edz", "versenyez",
        "utazik", "kirándul", "nyaral", "telel", "pihen", "szórakozik", "mulat", "ünnepel", "ajándékoz", "kíván",
   // melleknevek 
            "gyors", "lassú", "magas", "alacsony", "széles", "keskeny", "nagy", "kicsi", "erős", "gyenge",
            "szép", "csúnya", "okos", "buta", "gazdag", "szegény", "boldog", "szomorú", "fiatal", "idős",
            "új", "régi", "tiszta", "piszkos", "kemény", "puha", "hideg", "meleg", "forró", "hűvös",
            "világos", "sötét", "nehéz", "könnyű", "édes", "sós", "savanyú", "keserű", "száraz", "nedves",
            "éles", "tompa", "sim", "érdes", "széles", "keskeny", "vastag", "vékony", "mély", "sekély",
            "rövid", "hosszú", "szoros", "laza", "teli", "üres", "drága", "olcsó", "gyors", "lassú",
            "hangos", "csendes", "bátor", "félénk", "barátságos", "ellenséges", "kedves", "durva", "szorgalmas", "lusta",
            "egészséges", "beteg", "friss", "romlott", "száraz", "nedves", "tiszta", "piszkos", "szép", "csúnya",
            "okos", "buta", "gazdag", "szegény", "boldog", "szomorú", "fiatal", "idős", "új", "régi",
            "tiszta", "piszkos", "kemény", "puha", "hideg", "meleg", "forró", "hűvös", "világos", "sötét",
            "nehéz", "könnyű", "édes", "sós", "savanyú", "keserű", "száraz", "nedves", "éles", "tompa",
    // tárgyak
            "asztal", "szék", "lámpa", "ágy", "kanapé", "szekrény", "polc", "tükör", "ajtó", "ablak",
            "függöny", "szőnyeg", "párna", "takaró", "tányér", "pohár", "bögre", "villa", "kés", "kanál",
            "edény", "serpenyő", "fazék", "tepsi", "sütő", "mikrohullámú sütő", "hűtőszekrény", "mosógép", "szárítógép", "vasaló",
            "porszívó", "seprű", "lapát", "vödör", "felmosó", "szappan", "törölköző", "fogkefe", "fogkrém", "sampon",
            "fésű", "hajszárító", "borotva", "tükör", "szemüveg", "óra", "telefon", "számítógép", "laptop", "tablet",
            "billentyűzet", "egér", "monitor", "nyomtató", "hangszóró", "fülhallgató", "kamera", "tévé", "rádió", "DVD lejátszó",
            "könyv", "füzet", "ceruza", "toll", "radír", "hegyező", "vonalzó", "olló", "ragasztó", "tűzőgép",
            "papír", "boríték", "bélyeg", "naptár", "számológép", "táska", "hátizsák", "bőrönd", "esernyő", "kalap",
            "sapka", "sál", "kesztyű", "kabát", "pulóver", "nadrág", "szoknya", "ruha", "ing", "póló",
            "zokni", "cipő", "csizma", "papucs", "öv", "nyakkendő", "karóra", "gyűrű", "nyaklánc", "fülbevaló"
                     
];